set shell := ["bash", "-cu"]
set dotenv-load

main_model_dir := "outputs/bsbench/Qwen--Qwen3.5-9B-g2351502a"
main_report_dir := "outputs/bsbench/results/v5-9b-3seeds"

default:
	@just --list

check: smoke smoke-bsbench

# PI/OpenAI: real extract -> attach -> generate -> save/load for every registered method.
smoke:
	uv run --extra test --extra hf-test pytest -q tests/test_pipeline.py

# PI/OpenAI: real CPU walk, including both lower doses and legitimate controls.
smoke-bsbench method="mean_diff":
	uv run --extra benchmark python scripts/bsbench/walk.py {{method}} --smoke --preset tiny-random --n-pairs 4 --extract-batch-size 2 --max-length 256 --layers 1,2 --target-layer 4 --max-rungs 2 --controls

# PI/OpenAI: only the requested methods; main 9B setup, cached completed walks reused.
sweep methods cohort="full" seeds="0,1,2":
	uv run --extra benchmark modal run scripts/bsbench/run_modal.py::main --cohort {{cohort}} --methods {{methods}} --seeds {{seeds}} --extra "--preset qwen3.5-9b --pairs bsbench_v1 --controls"

# PI/OpenAI: random has no control penalty; keep this reference separate from learned methods.
sweep-random cohort="full" seeds="auto":
	uv run --extra benchmark modal run scripts/bsbench/run_modal.py::main --cohort {{cohort}} --methods random --seeds {{seeds}} --extra "--preset qwen3.5-9b --pairs bsbench_v1"

pull:
	uv run --extra benchmark modal volume get --force steering-lite-bsbench-v3 bsbench outputs/

# PI/OpenAI: one canonical 9B report, generated by maintained code rather than slop scripts.
results:
	uv run --extra benchmark python scripts/bsbench/judge.py --cohort full --model-dir {{main_model_dir}} --refresh
	uv run --extra benchmark python scripts/bsbench/results.py --cohort full --model-dir {{main_model_dir}} --out {{main_report_dir}}
	cd scripts/bsbench/web && pnpm install --frozen-lockfile --silent && pnpm exec vite build --outDir ../../../{{main_report_dir}} --emptyOutDir false
	uv run --with playwright python scripts/bsbench/web/uat.py {{main_report_dir}}
	mkdir -p assets/bsbench
	cp {{main_report_dir}}/plot.png assets/bsbench/qwen3.5-9b.png
