set shell := ["bash", "-cu"]
set dotenv-load

main_model_dir := "outputs/bsbench/Qwen--Qwen3.5-9B-g2351502a"
main_report_dir := "outputs/bsbench/results/v5-9b-3seeds"
dev_report_dir := "outputs/bsbench/results/v5-9b-dev"

default:
	@just --list

check: smoke smoke-bsbench

# PI/OpenAI: real extract -> attach -> generate -> save/load for every registered method.
smoke:
	uv run --extra test --extra hf-test pytest -q tests/test_pipeline.py

# PI/OpenAI: real CPU walk, including both lower doses and legitimate controls.
smoke-bsbench method="mean_diff":
	uv run --extra benchmark python scripts/bsbench/walk.py {{method}} --smoke --preset tiny-random --n-pairs 4 --extract-batch-size 2 --max-length 256 --layers 1,2 --target-layer 4 --max-rungs 2 --controls

# PI/OpenAI: only the requested methods; main 9B setup, cached completed walks reused.
sweep methods cohort="full" seeds="0,1,2":
	uv run --extra benchmark modal run scripts/bsbench/run_modal.py::main --cohort {{cohort}} --methods {{methods}} --seeds {{seeds}} --extra "--preset qwen3.5-9b --pairs bsbench_v1 --controls"

# PI/OpenAI: random has no control penalty; keep this reference separate from learned methods.
sweep-random cohort="full" seeds="auto":
	uv run --extra benchmark modal run scripts/bsbench/run_modal.py::main --cohort {{cohort}} --methods random --seeds {{seeds}} --extra "--preset qwen3.5-9b --pairs bsbench_v1"

# PI/OpenAI: try a new method on 9B, 1 seed, 20 questions; compared with every finished method sliced to the same questions.
dev method:
	just sweep {{method}} dev 0
	just pull
	just dev-results {{method}}

# PI/OpenAI: judge and render the dev page without new GPU work.
dev-results method="":
	uv run --extra benchmark python scripts/bsbench/judge.py --cohort dev --model-dir {{main_model_dir}} --refresh
	uv run --extra benchmark python scripts/bsbench/results.py --cohort dev --model-dir {{main_model_dir}} --out {{dev_report_dir}} --show "{{method}}"
	cd scripts/bsbench/web && pnpm install --frozen-lockfile --silent && pnpm exec vite build --outDir ../../../{{dev_report_dir}} --emptyOutDir false
	uv run --with playwright python scripts/bsbench/web/uat.py {{dev_report_dir}}

pull:
	uv run --extra benchmark modal volume get --force steering-lite-bsbench-v3 bsbench outputs/

# PI/OpenAI: one canonical 9B report, generated by maintained code rather than slop scripts.
results:
	uv run --extra benchmark python scripts/bsbench/judge.py --cohort full --model-dir {{main_model_dir}} --refresh
	uv run --extra benchmark python scripts/bsbench/results.py --cohort full --model-dir {{main_model_dir}} --out {{main_report_dir}} --readme-table docs/readme/includes/results_table.md
	cd scripts/bsbench/web && pnpm install --frozen-lockfile --silent && pnpm exec vite build --outDir ../../../{{main_report_dir}} --emptyOutDir false
	uv run --with playwright python scripts/bsbench/web/uat.py {{main_report_dir}}
	mkdir -p assets/bsbench
	cp {{main_report_dir}}/plot_readme.png assets/bsbench/qwen3.5-9b.png
	just docs

# PI/OpenAI: README.md is generated from README.qmd (edit the .qmd); the table comes from `just results`.
docs:
	quarto render README.qmd --to all
	quarto pandoc README.md -f gfm -t gfm --wrap=none --lua-filter docs/readme/flatten-xref.lua -o README.md
	sed -i 's/\\[[]/[/g; s/\\[]]/]/g' README.md

# PI/OpenAI: publish the main 9B page to GitHub Pages (gh-pages branch, one orphan commit, force-pushed so old sites do not pile up).
pages_url := "https://wassname.github.io/steering-lite/bsbench/qwen3.5-9b/"
publish:
	rm -rf .local/pages && mkdir -p .local/pages/bsbench/qwen3.5-9b
	cp -r {{main_report_dir}}/index.html {{main_report_dir}}/assets {{main_report_dir}}/points.json {{main_report_dir}}/answers {{main_report_dir}}/plot.png {{main_report_dir}}/controls.png {{main_report_dir}}/controls.html .local/pages/bsbench/qwen3.5-9b/
	touch .local/pages/.nojekyll
	printf '<meta http-equiv="refresh" content="0; url=bsbench/qwen3.5-9b/">\n' > .local/pages/index.html
	cd .local/pages && git init -q -b gh-pages && git add -A && git commit -qm "Publish main 9B BS-bench page from $(git -C ../.. rev-parse --short HEAD)" && git push -qf https://github.com/wassname/steering-lite.git gh-pages
	du -sh .local/pages
	@echo "PUBLISHED {{pages_url}}"
