"""Iso on-policy KL calibration: find the coeff per method that produces a target
mean KL(steer || base) over the first T_CALIB tokens of on-policy SAMPLED generation.

Why:
- Free-dNLL calibration scores steered model on tokens generated by BASE (off-policy).
- This misses the divergence introduced by steering's own trajectory drift.
- On-policy sampling is what users actually deploy, so calibrate where you live.

Algorithm: for each coeff,
  1. With steering attached, sample T_CALIB tokens from steered model at temp=1.
  2. Forward those tokens through base (steering detached) and steer (attached).
  3. Compute per-position KL_sb = sum p_steer (logp_steer - logp_base) for t∈[0,T_CALIB).
  4. Aggregate (mean across position+prompts).
Bisect coeff so this aggregate equals target.

Bound interpretation (Markov on log-ratio):
  If mean per-token KL_sb = D, then under p_steer
  P[log(p_steer/p_base) > τ] ≤ D/τ
  → at D=0.3, ≤10% of sampled tokens are 20× less likely under base.

Cost: T_CALIB=20 × N_calib=4 × ~12 bisection iters × 2 forward passes ≈ 1/3 of free-dNLL.

Usage:
    python scripts/iso_kl_sampled.py --model Qwen/Qwen3.5-0.8B --layers 4 --target-kl 0.3 \\
        --t-calib 20 --n-calib 4 --chat-template --enable-thinking
"""
from __future__ import annotations
import argparse
import json
import random
import time
from pathlib import Path

import torch
from loguru import logger

import steering_lite as sl
from steering_lite.daily_dilemmas import load_pairs, make_prompt


METHODS = ["mean_diff", "pca", "topk_clusters", "cosine_gated", "sspace", "spherical"]


def make_cfg(method: str, layers: tuple[int, ...], coeff: float, dtype, seed: int, n_train: int):
    common = dict(layers=layers, coeff=coeff, dtype=dtype, seed=seed)
    table = {
        "mean_diff": sl.MeanDiffConfig(**common),
        "pca": sl.PCAConfig(**common),
        "topk_clusters": sl.TopKClustersConfig(**common, k=min(n_train, 4)),
        "cosine_gated": sl.CosineGatedConfig(**common, tau=0.0),
        "sspace": sl.SSpaceConfig(**common, r=min(n_train, 4)),
        "spherical": sl.SphericalConfig(**common),
    }
    return table[method]


def build_prompts(tok, situations: list[str], chat: bool, enable_thinking: bool) -> list[torch.Tensor]:
    """Tokenize prompts. If chat=True, wrap in chat template."""
    out = []
    for s in situations:
        if chat:
            messages = [{"role": "user", "content": s}]
            text = tok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True,
                                           enable_thinking=enable_thinking)
        else:
            text = make_prompt(s)
        ids = tok(text, return_tensors="pt", truncation=True, max_length=512).input_ids[0]
        out.append(ids)
    return out


@torch.no_grad()
def sample_onpolicy(model, prompt_ids: torch.Tensor, T: int, eos_id, pad_id,
                    temperature: float, top_p: float, top_k: int, device) -> torch.Tensor:
    """Sample T tokens from the model with steering currently attached.
    Returns generated token ids [T] (no prompt)."""
    ids = prompt_ids.unsqueeze(0).to(device)
    out = model.generate(
        ids, max_new_tokens=T,
        do_sample=True, temperature=temperature, top_p=top_p, top_k=top_k,
        pad_token_id=pad_id, eos_token_id=eos_id,
        num_return_sequences=1,
    )
    return out[0, prompt_ids.shape[0]:]  # [T] generated only (may be < T if eos)


@torch.no_grad()
def kl_at_positions(logp_steer: torch.Tensor, logp_base: torch.Tensor) -> torch.Tensor:
    """KL(p_steer || p_base) per position. Inputs [T, V] log-probs. Returns [T]."""
    p_s = logp_steer.exp()
    return (p_s * (logp_steer - logp_base)).sum(dim=-1)


@torch.no_grad()
def measure_onpolicy_kl(model, prompts: list[torch.Tensor], T: int, vectors, s_cfg,
                        eos_id, pad_id, temperature: float, top_p: float, top_k: int,
                        device) -> dict:
    """For each prompt: sample T tokens with steering, then score under base+steer.
    Return per-position KL_sb across all (prompt, position) pairs."""
    all_kls = []
    for pids in prompts:
        # 1. sample on-policy with steering
        sl.attach(model, s_cfg, vectors)
        try:
            gen = sample_onpolicy(model, pids, T, eos_id, pad_id, temperature, top_p, top_k, device)
        finally:
            sl.detach(model)
        n_gen = gen.shape[0]
        if n_gen == 0:
            continue
        full = torch.cat([pids.to(device), gen]).unsqueeze(0)  # [1, P+T]
        n_p = pids.shape[0]
        # 2. score under base
        logits_base = model(full).logits.float()
        logp_base = torch.log_softmax(logits_base, dim=-1)[0]  # [P+T, V]
        # 3. score under steer
        sl.attach(model, s_cfg, vectors)
        try:
            logits_steer = model(full).logits.float()
        finally:
            sl.detach(model)
        logp_steer = torch.log_softmax(logits_steer, dim=-1)[0]
        # 4. KL at positions that predict gen[0..T-1] (i.e. logits at indices [n_p-1..n_p+T-2])
        slc = slice(n_p - 1, n_p - 1 + n_gen)
        kls = kl_at_positions(logp_steer[slc], logp_base[slc])  # [T]
        all_kls.append(kls.cpu())
    cat = torch.cat(all_kls)
    return {
        "kl_mean": float(cat.mean()),
        "kl_p50": float(cat.quantile(0.50)),
        "kl_p90": float(cat.quantile(0.90)),
        "n_pos": int(cat.numel()),
    }


def calibrate(model, method: str, layers, dtype, seed: int, n_train: int,
              vectors, prompts, T: int, target_kl: float, eos_id, pad_id,
              temperature: float, top_p: float, top_k: int, device,
              tol: float = 0.02, max_iters: int = 12) -> tuple[float, dict, list]:
    is_spherical = method == "spherical"
    if is_spherical:
        lo, hi = 0.001, 0.5
    else:
        lo, hi = 0.05, 16.0

    history = []
    def eval_at(c):
        s_cfg = make_cfg(method, layers, c, dtype, seed, n_train)
        m = measure_onpolicy_kl(model, prompts, T, vectors, s_cfg, eos_id, pad_id,
                                temperature, top_p, top_k, device)
        history.append({"coeff": c, **m})
        logger.info(f"  [{method}] c={c:.4f} kl_mean={m['kl_mean']:.4f} "
                    f"kl_p50={m['kl_p50']:.4f} kl_p90={m['kl_p90']:.4f} n={m['n_pos']}")
        return m["kl_mean"]

    # Exponential bracket
    mid = (lo * hi) ** 0.5
    v_mid = eval_at(mid)
    if v_mid < target_kl:
        c = mid
        while c < hi:
            c *= 2.0
            v = eval_at(c)
            if v >= target_kl:
                lo, hi = c / 2.0, c
                break
        else:
            return c, history[-1], history
    else:
        c = mid
        while c > lo:
            c /= 2.0
            v = eval_at(c)
            if v <= target_kl:
                lo, hi = c, c * 2.0
                break
        else:
            return c, history[-1], history

    # Bisect
    for _ in range(max_iters):
        m = (lo + hi) / 2.0
        v = eval_at(m)
        if abs(v - target_kl) < tol:
            lo = hi = m
            break
        if v < target_kl:
            lo = m
        else:
            hi = m

    final_c = (lo + hi) / 2.0
    return final_c, history[-1], history


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--model", required=True)
    p.add_argument("--target", default="honesty")
    p.add_argument("--layers", default="4")
    p.add_argument("--target-kl", type=float, default=0.3, help="mean per-token KL_sb target [nats]")
    p.add_argument("--t-calib", type=int, default=20, help="number of generated tokens to score per prompt")
    p.add_argument("--n-calib", type=int, default=4, help="number of calibration prompts")
    p.add_argument("--n-train", type=int, default=64)
    p.add_argument("--seeds", default="0", help="comma-separated seeds")
    p.add_argument("--device", default="cuda")
    p.add_argument("--torch-dtype", default="bfloat16")
    p.add_argument("--methods", default=",".join(METHODS))
    p.add_argument("--temperature", type=float, default=1.0)
    p.add_argument("--top-p", type=float, default=1.0)
    p.add_argument("--top-k", type=int, default=20)
    p.add_argument("--chat-template", action="store_true")
    p.add_argument("--enable-thinking", action="store_true")
    p.add_argument("--output-dir", default="outputs/iso_kl")
    args = p.parse_args()

    layers = tuple(int(x) for x in args.layers.split(","))
    dtype = getattr(torch, args.torch_dtype)
    methods = args.methods.split(",")
    seeds = [int(s) for s in args.seeds.split(",")]
    out_dir = Path(args.output_dir); out_dir.mkdir(parents=True, exist_ok=True)

    from transformers import AutoModelForCausalLM, AutoTokenizer
    logger.info(f"loading model={args.model}")
    tok = AutoTokenizer.from_pretrained(args.model)
    if tok.pad_token is None: tok.pad_token = tok.eos_token or tok.unk_token or "<pad>"
    eos_id = tok.eos_token_id
    pad_id = tok.pad_token_id
    model = AutoModelForCausalLM.from_pretrained(args.model, torch_dtype=dtype).to(args.device).eval()

    all_summary = []
    for seed in seeds:
        logger.info(f"########## seed={seed} ##########")
        random.seed(seed); torch.manual_seed(seed)

        pairs = load_pairs(args.target, seed=seed)
        train_pairs = pairs[: args.n_train]
        calib_pairs = pairs[args.n_train : args.n_train + args.n_calib]
        pos = [make_prompt(pp.situation) + pp.action_pos for pp in train_pairs]
        neg = [make_prompt(pp.situation) + pp.action_neg for pp in train_pairs]
        logger.info(f"target={args.target} n_train={len(pos)} n_calib={len(calib_pairs)}")

        prompts = build_prompts(tok, [pp.situation for pp in calib_pairs],
                                args.chat_template, args.enable_thinking)
        logger.info(f"calib prompts ready: {len(prompts)} (chat={args.chat_template} think={args.enable_thinking})")

        for method in methods:
            logger.info(f"=== seed={seed} {method} target={args.target_kl} ===")
            s_cfg0 = make_cfg(method, layers, 1.0, dtype, seed, args.n_train)
            vectors = sl.train(model, tok, pos, neg, s_cfg0, batch_size=4, max_length=256)
            torch.manual_seed(seed)  # reset for sampling determinism inside calibrate
            c, final_m, history = calibrate(
                model, method, layers, dtype, seed, args.n_train,
                vectors, prompts, args.t_calib, args.target_kl, eos_id, pad_id,
                args.temperature, args.top_p, args.top_k, args.device,
            )
            best = min(history, key=lambda h: abs(h["kl_mean"] - args.target_kl))
            row = {
                "model": args.model, "method": method, "seed": seed,
                "calibrated_coeff": best["coeff"],
                "kl_mean": best["kl_mean"], "kl_p50": best["kl_p50"], "kl_p90": best["kl_p90"],
                "iters": len(history),
                "history": history,
            }
            all_summary.append(row)
            logger.info(f"[seed={seed} {method}] coeff*={best['coeff']:.4f} "
                        f"kl_mean={best['kl_mean']:.4f} p50={best['kl_p50']:.4f} p90={best['kl_p90']:.4f}")

    out_path = out_dir / (
        f"iso_kl__{args.model.replace('/', '--')}__L{'_'.join(map(str, layers))}"
        f"__klm{args.target_kl}__T{args.t_calib}__N{args.n_calib}"
        f"__seeds{args.seeds.replace(',', '_')}__{int(time.time())}.json"
    )
    out_path.write_text(json.dumps({"args": vars(args), "summary": all_summary}, indent=2))
    logger.info(f"wrote {out_path}")
    print("\n| seed | method | coeff* | kl_mean | kl_p50 | kl_p90 | iters |")
    print("|---:|---|---:|---:|---:|---:|---:|")
    for r in all_summary:
        print(f"| {r['seed']} | {r['method']} | {r['calibrated_coeff']:.4f} | "
              f"{r['kl_mean']:.3f} | {r['kl_p50']:.3f} | {r['kl_p90']:.3f} | {r['iters']} |")


if __name__ == "__main__":
    main()
